In [1]:
import numpy as np
import pandas as pd

In [2]:
gpay = pd.read_csv('GooglePayIndia.csv', sep=',')
gpay

,Unnamed: 0,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,0,gp:AOqpTOEdT_VactGi_J9Q2PEWY7J4XlD7BINhOj9xwOr...,Len Pagnam,https://play-lh.googleusercontent.com/a-/AOh14...,How do add a boarding pass? I see no passes tab.,1,0,2.137.401329300,2021-11-18 17:03:06,Hi Len. Could you try the steps in this guide ...,2021-11-18 17:27:11
1,1,gp:AOqpTOHltpCzXurPoFUgj-a3L-wApC93-fTvocbF9K7...,Benjamin Silva,https://play-lh.googleusercontent.com/a/AATXAJ...,Best,5,0,2.134.392709498,2021-11-18 16:43:34,NaN,NaN
2,2,gp:AOqpTOGTiyxy_FWSQe7eCONa7PsIP6v7cS-xWCL6jFF...,PARVESH MIAR,https://play-lh.googleusercontent.com/a-/AOh14...,All ok,5,0,2.138.406141160,2021-11-18 16:12:42,NaN,NaN
3,3,gp:AOqpTOHllyGnmLGZqPUGokxYncq9kOKoY3Zz_4ZF6b0...,Mikko L.,https://play-lh.googleusercontent.com/a-/AOh14...,"Rasy to use really... But there never, ever sh...",3,0,2.138.406141160,2021-11-18 16:06:35,NaN,NaN
4,4,gp:AOqpTOHjnJ6gAF4NzruhLDGVszAaTKSerVeKt-UtJfM...,A Google user,https://play-lh.googleusercontent.com/EGemoI2N...,I still do not understand why your restricting...,3,251,2.134.392709498,2021-11-18 15:48:08,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
34223,34223,gp:AOqpTOEXYnopFG3RZ8fVrBC9yqXnVjmhnDI0Ji99tXb...,Daran Smith,https://play-lh.googleusercontent.com/a-/AOh14...,Like it good app,5,0,2.96.264233179,2019-10-01 02:47:10,NaN,NaN
34224,34224,gp:AOqpTOEVXSkb09ThJsY2TZ0awLgMSCO0qzySxtcT7x9...,Judi Anne,https://play-lh.googleusercontent.com/a-/AOh14...,Excellent very easy to use,5,0,2.95.262992467,2019-10-01 02:38:48,NaN,NaN
34225,34225,gp:AOqpTOHv3DyIxgg2a61I_QQGgjbFodIUp6UlaUpd4M9...,Noori Lal,https://play-lh.googleusercontent.com/a-/AOh14...,Easy to use.,5,0,2.96.264233179,2019-10-01 02:17:54,NaN,NaN
34226,34226,gp:AOqpTOHEnAmESklDXdnvO13QBDl9gOlH4M1qQs-gMYS...,Josh Phillips,https://play-lh.googleusercontent.com/a-/AOh14...,Works how it should,5,0,2.96.264233179,2019-10-01 02:09:34,NaN,NaN
34227,34227,gp:AOqpTOHfgaMoLANmo4v7W91hqWvHFJ7ogUmKQ7fvcNo...,Saeed Aljasmi,https://play-lh.googleusercontent.com/a/AATXAJ...,Best,5,0,2.96.264233179,2019-10-01 02:06:57,NaN,NaN

In [3]:
gpay = gpay.rename(columns={'Unnamed: 0' : 'id',
                            'userName' : 'username',
                            'thumbsUpCount' : 'thumbsups',
                            'at' : 'time',
                            'replyContent' : 'reply',
                            'repliedat' : 'reply_time'})

In [4]:
gpay = gpay.drop(columns=['reviewId','userImage'])

In [5]:
gpay

,id,username,content,score,thumbsups,reviewCreatedVersion,time,reply,repliedAt
0,0,Len Pagnam,How do add a boarding pass? I see no passes tab.,1,0,2.137.401329300,2021-11-18 17:03:06,Hi Len. Could you try the steps in this guide ...,2021-11-18 17:27:11
1,1,Benjamin Silva,Best,5,0,2.134.392709498,2021-11-18 16:43:34,NaN,NaN
2,2,PARVESH MIAR,All ok,5,0,2.138.406141160,2021-11-18 16:12:42,NaN,NaN
3,3,Mikko L.,"Rasy to use really... But there never, ever sh...",3,0,2.138.406141160,2021-11-18 16:06:35,NaN,NaN
4,4,A Google user,I still do not understand why your restricting...,3,251,2.134.392709498,2021-11-18 15:48:08,NaN,NaN
...,...,...,...,...,...,...,...,...,...
34223,34223,Daran Smith,Like it good app,5,0,2.96.264233179,2019-10-01 02:47:10,NaN,NaN
34224,34224,Judi Anne,Excellent very easy to use,5,0,2.95.262992467,2019-10-01 02:38:48,NaN,NaN
34225,34225,Noori Lal,Easy to use.,5,0,2.96.264233179,2019-10-01 02:17:54,NaN,NaN
34226,34226,Josh Phillips,Works how it should,5,0,2.96.264233179,2019-10-01 02:09:34,NaN,NaN
34227,34227,Saeed Aljasmi,Best,5,0,2.96.264233179,2019-10-01 02:06:57,NaN,NaN

In [6]:
gpay['time'] = pd.to_datetime(gpay['time'])  
gpay['year'] = gpay['time'].dt.year
gpay['month'] = gpay['time'].dt.month
gpay['month_name'] = gpay['time'].dt.month_name()
gpay['day'] = gpay['time'].dt.day
gpay['day_name'] = gpay['time'].dt.day_name()
gpay['hour'] = gpay['time'].dt.hour

gpay['repliedAt'] = pd.to_datetime(gpay['repliedAt'])  
gpay['reply_yr'] = gpay['repliedAt'].dt.year
gpay['reply_month'] = gpay['repliedAt'].dt.month
gpay['reply_month_name'] = gpay['repliedAt'].dt.month_name()
gpay['reply_day'] = gpay['repliedAt'].dt.day
gpay['reply_day_name'] = gpay['repliedAt'].dt.day_name()
gpay['reply_hour'] = gpay['repliedAt'].dt.hour

In [7]:
gpay

,id,username,content,score,thumbsups,reviewCreatedVersion,time,reply,repliedAt,year,...,month_name,day,day_name,hour,reply_yr,reply_month,reply_month_name,reply_day,reply_day_name,reply_hour
0,0,Len Pagnam,How do add a boarding pass? I see no passes tab.,1,0,2.137.401329300,2021-11-18 17:03:06,Hi Len. Could you try the steps in this guide ...,2021-11-18 17:27:11,2021,...,November,18,Thursday,17,2021.0,11.0,November,18.0,Thursday,17.0
1,1,Benjamin Silva,Best,5,0,2.134.392709498,2021-11-18 16:43:34,NaN,NaT,2021,...,November,18,Thursday,16,NaN,NaN,NaN,NaN,NaN,NaN
2,2,PARVESH MIAR,All ok,5,0,2.138.406141160,2021-11-18 16:12:42,NaN,NaT,2021,...,November,18,Thursday,16,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Mikko L.,"Rasy to use really... But there never, ever sh...",3,0,2.138.406141160,2021-11-18 16:06:35,NaN,NaT,2021,...,November,18,Thursday,16,NaN,NaN,NaN,NaN,NaN,NaN
4,4,A Google user,I still do not understand why your restricting...,3,251,2.134.392709498,2021-11-18 15:48:08,NaN,NaT,2021,...,November,18,Thursday,15,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34223,34223,Daran Smith,Like it good app,5,0,2.96.264233179,2019-10-01 02:47:10,NaN,NaT,2019,...,October,1,Tuesday,2,NaN,NaN,NaN,NaN,NaN,NaN
34224,34224,Judi Anne,Excellent very easy to use,5,0,2.95.262992467,2019-10-01 02:38:48,NaN,NaT,2019,...,October,1,Tuesday,2,NaN,NaN,NaN,NaN,NaN,NaN
34225,34225,Noori Lal,Easy to use.,5,0,2.96.264233179,2019-10-01 02:17:54,NaN,NaT,2019,...,October,1,Tuesday,2,NaN,NaN,NaN,NaN,NaN,NaN
34226,34226,Josh Phillips,Works how it should,5,0,2.96.264233179,2019-10-01 02:09:34,NaN,NaT,2019,...,October,1,Tuesday,2,NaN,NaN,NaN,NaN,NaN,NaN
34227,34227,Saeed Aljasmi,Best,5,0,2.96.264233179,2019-10-01 02:06:57,NaN,NaT,2019,...,October,1,Tuesday,2,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
gpay.columns

Index(['id', 'username', 'content', 'score', 'thumbsups',
       'reviewCreatedVersion', 'time', 'reply', 'repliedAt', 'year', 'month',
       'month_name', 'day', 'day_name', 'hour', 'reply_yr', 'reply_month',
       'reply_month_name', 'reply_day', 'reply_day_name', 'reply_hour'],
      dtype='object')

## 🧠 A. Product Satisfaction Insights

### Q1. What is the true overall perception of Google Pay — loved, acceptable, or frustrating?

In [9]:
gpay['score'].describe()

count    34228.000000
mean         3.651689
std          1.715733
min          1.000000
25%          1.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: score, dtype: float64

### Q2. Is the app polarized (many 1★ & 5★ but fewer middle ratings)?

In [10]:
extreme = gpay[gpay['score'].isin([1,5])].shape[0]

In [11]:
mid = gpay[gpay['score'].isin([2,3,4])].shape[0]

In [12]:
(extreme / (extreme+mid)) * 100

80.82271824237466

### Q3. Do users mostly complain or mostly appreciate?

In [13]:
gpay['sentiment'] = gpay['score'].apply(lambda x:'Positive' if x>=4 else 'Neutral' if x==3 else 'Negative')
gpay['sentiment'].value_counts()

sentiment
Positive    22089
Negative    10211
Neutral      1928
Name: count, dtype: int64

### Q4. Are negative reviews dominating the conversation?

In [14]:
gpay['sentiment'].value_counts()

sentiment
Positive    22089
Negative    10211
Neutral      1928
Name: count, dtype: int64

### Q5. Are users more vocal when angry than when happy?

In [15]:
gpay.groupby('score')['content'].count()

score
1     8616
2     1592
3     1928
4     3042
5    19041
Name: content, dtype: int64

### Q6. Do helpful votes support complaints more than praise?

In [16]:
gpay.groupby('score')['thumbsups'].mean()

score
1     5.824321
2    10.360326
3     5.942946
4     4.075583
5     1.603014
Name: thumbsups, dtype: float64

### Q7. Which rating actually influences other users the most?

In [17]:
gpay.groupby('score')['thumbsups'].sum()

score
1    50194
2    16504
3    11458
4    12402
5    30531
Name: thumbsups, dtype: int64

## ⏰ B. Reliability & Failure Timing

### Q8. At what time of day do failures most likely happen?

In [18]:
gpay[gpay['score']==1]['hour'].value_counts().sort_values(ascending=False)

hour
0     477
3     467
1     454
2     440
23    431
22    425
20    424
4     423
21    409
19    383
5     371
18    369
8     343
6     327
17    323
16    304
15    296
12    293
7     291
9     286
14    284
11    275
13    263
10    260
Name: count, dtype: int64

### Q9. Are late-night transactions riskier?

In [19]:
gpay['late_night'] = gpay['hour'].apply(lambda x: 'Late-Night' if x<6 or x>=23 else 'Day')
gpay.groupby('late_night')['score'].mean()

late_night
Day           3.646810
Late-Night    3.660704
Name: score, dtype: float64

### 10. Do weekends produce more complaints?

In [20]:
gpay['week'] = gpay['day_name'].apply(lambda x: 'Weekend' if x in ['Saturday', 'Sunday'] else 'Weekday')
gpay.groupby('week')['thumbsups'].mean()

week
Weekday    3.443857
Weekend    3.783105
Name: thumbsups, dtype: float64

### Q11. Is there a specific “danger window” for transactions?

In [21]:
gpay.groupby('hour')['score'].mean()

hour
0     3.622370
1     3.661444
2     3.659550
3     3.615741
4     3.647273
5     3.672691
6     3.751949
7     3.740260
8     3.614722
9     3.649047
10    3.666354
11    3.571977
12    3.527493
13    3.608083
14    3.550871
15    3.627133
16    3.617162
17    3.691395
18    3.627547
19    3.662442
20    3.620668
21    3.681845
22    3.694886
23    3.744097
Name: score, dtype: float64

### Q12. Do ratings drop during peak usage hours?

In [22]:
review_by_hr = gpay['hour'].value_counts()
rating_by_hr = gpay.groupby('hour')['score'].mean()
pd.concat([review_by_hr, rating_by_hr], axis=1)

      count     score
hour
23     1821  3.744097
0      1806  3.622370
1      1787  3.661444
22     1760  3.694886
2      1733  3.659550
3      1728  3.615741
21     1691  3.681845
4      1650  3.647273
20     1616  3.620668
19     1499  3.662442
5      1494  3.672691
18     1423  3.627547
6      1411  3.751949
17     1348  3.691395
7      1309  3.740260
8      1277  3.614722
16     1212  3.617162
15     1172  3.627133
9      1154  3.649047
14     1091  3.550871
12     1073  3.527493
10     1067  3.666354
13     1064  3.608083
11     1042  3.571977

### Q13. Do users complain immediately after payment time (evenings)?

In [23]:
gpay[gpay['hour'].between(18,23)]['score'].value_counts()

score
5    5556
1    2441
4     849
3     505
2     459
Name: count, dtype: int64

### Q14. Are mornings mostly positive usage feedback?

In [24]:
gpay[gpay['hour'].between(4,9)]['score'].value_counts()

score
5    4682
1    2041
4     720
3     487
2     365
Name: count, dtype: int64

## 📆 C. Product Stability Over Time

### Q15. Is the product improving month over month?

In [25]:
gpay.groupby(['year','month'])['score'].mean()

year  month
2019  10       4.143862
      11       4.173575
      12       4.117181
2020  1        4.064246
      2        4.124884
      3        4.092952
      4        4.001482
      5        4.099078
      6        3.926300
      7        3.612859
      8        3.354151
      9        3.335187
      10       3.355476
      11       3.140555
      12       2.924888
2021  1        2.813783
      2        2.941807
      3        3.031532
      4        2.890302
      5        2.934307
      6        2.826316
      7        2.603175
      8        2.688293
      9        2.737338
      10       2.780323
      11       2.835586
Name: score, dtype: float64

### Q16. Did a certain month damage user trust?

In [26]:
gpay.groupby('month_name')['score'].mean().sort_values(ascending=False)

month_name
February     3.849662
December     3.780835
May          3.779078
January      3.762898
March        3.761771
April        3.738032
November     3.722724
October      3.715677
June         3.680517
July         3.354018
August       3.120673
September    3.094402
Name: score, dtype: float64

### Q17. Do ratings fluctuate seasonally?

In [27]:
gpay.groupby('month')['score'].std()

month
1     1.688326
2     1.637993
3     1.681124
4     1.700294
5     1.661507
6     1.712082
7     1.765027
8     1.804189
9     1.781385
10    1.689477
11    1.689442
12    1.681648
Name: score, dtype: float64

### Q18. Are complaints increasing faster than reviews?

In [28]:
gpay[gpay['score']==1].groupby(['year','month']).size()

year  month
2019  10       364
      11       327
      12       367
2020  1        351
      2        323
      3        312
      4        375
      5        341
      6        384
      7        366
      8        415
      9        389
      10       337
      11       392
      12       369
2021  1        316
      2        261
      3        348
      4        263
      5        321
      6        246
      7        233
      8        316
      9        369
      10       339
      11       194
dtype: int64

### Q19. Does the app become unstable after updates (sudden rating dips)?

In [29]:
gpay.groupby(['year','month'])['score'].mean().diff()

year  month
2019  10            NaN
      11       0.029713
      12      -0.056395
2020  1       -0.052935
      2        0.060638
      3       -0.031932
      4       -0.091470
      5        0.097596
      6       -0.172778
      7       -0.313441
      8       -0.258708
      9       -0.018964
      10       0.020289
      11      -0.214921
      12      -0.215667
2021  1       -0.111105
      2        0.128024
      3        0.089724
      4       -0.141229
      5        0.044005
      6       -0.107991
      7       -0.223141
      8        0.085119
      9        0.049045
      10       0.042985
      11       0.055262
Name: score, dtype: float64

## 👍 D. Community Agreement (Thumbsups)

### Q20. Do users collectively agree with negative feedback?

In [30]:
gpay.groupby('sentiment')['thumbsups'].mean()

sentiment
Negative    6.531975
Neutral     5.942946
Positive    1.943637
Name: thumbsups, dtype: float64

### Q21. Which type of review becomes “trusted opinion”?

In [31]:
gpay.sort_values('thumbsups',ascending=False)[['score','thumbsups','sentiment']].head(10)

       score  thumbsups sentiment
15523      2       1921  Negative
1784       1       1733  Negative
16863      2       1491  Negative
1897       1       1216  Negative
13143      5        976  Positive
32734      1        973  Negative
30715      5        840  Positive
33782      4        775  Positive
3698       1        721  Negative
15513      2        714  Negative

### Q22. Are short reactions ignored compared to detailed complaints?

In [32]:
gpay['length'] = gpay['content'].astype(str).str.len()

In [33]:
gpay.groupby(pd.qcut(gpay['length'], 4))['thumbsups'].mean()

C:\Users\HP\AppData\Local\Temp\ipykernel_18468\2203217553.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  gpay.groupby(pd.qcut(gpay['length'], 4))['thumbsups'].mean()

length
(0.999, 13.0]       0.099988
(13.0, 37.0]        0.216082
(37.0, 103.0]       0.860528
(103.0, 1836.0]    13.000117
Name: thumbsups, dtype: float64

### Q23. Do viral complaints represent real issues or rare issues?

In [34]:
gpay[gpay['thumbsups'] > gpay['thumbsups'].quantile(0.99)][['score','content']]

       score                                            content
4          3  I still do not understand why your restricting...
213        1  The old app worked perfectly in Australia. The...
588        5  Works good. Phone just has to be unlocked to w...
832        1  I just found out that I can pay through my pho...
960        1  It removes my cards from the list, it has happ...
...      ...                                                ...
33272      5  Can't fault this app after quite a few months ...
33396      3  Only keeps history of payments for a week or t...
33525      1  Used Google Pay for years and for no reason I ...
33771      1  Very disappointed with the app. On paper disco...
33782      4  I like that google services are all connected....

[338 rows x 2 columns]

## 📝 E. Behaviour of Angry vs Happy Users

### Q24. Are angry users writing longer reviews?

In [35]:
gpay.groupby('score')['length'].mean()

score
1    136.384776
2    146.785311
3    121.507261
4     80.719685
5     46.135409
Name: length, dtype: float64

### Q25. Are happy users brief?

In [36]:
gpay[gpay['score']==5]['length'].mean()

np.float64(46.13540900976583)

### Q26. Do satisfied users explain why they like the app?

In [37]:
gpay[gpay['score']>=4]['content'].head(20)

1                                                  Best
2                                                All ok
6     No ticket/transport support for Europe. Also n...
7     App is now working for me as expected. Google ...
8                                                  Good
10                                                  Ok!
11    Love this app easy to 7se and helps keep every...
12                            It's amazing apps😍🤩🤩🤩🤩🤩🤩🤩
13    I'm getting Google Play Services crashed every...
14                                    Useful & good app
16    Before covid i was using google pay and samsun...
18                                    It's a good App 👍
19                                              Good A+
21                                            Great app
24                                                 Good
25    I loved the idea of having a separate Apps; On...
26                   Super convenient, fast and secure.
27             Home screen shortcuts keep disappearing.
28                                 Works great thankyou
29    Very simple, just get the job done with no mor...
Name: content, dtype: object

### Q27. Do frustrated users describe specific failures (refund / bank / server / OTP)?

In [38]:
from collections import Counter
words = ' '.join(gpay[gpay['score']==1]['content'].astype(str)).lower().split()
Counter(words).most_common(10)

[('to', 7795),
 ('i', 6918),
 ('the', 6115),
 ('my', 5083),
 ('it', 4648),
 ('and', 4635),
 ('a', 3322),
 ('not', 2820),
 ('google', 2716),
 ('is', 2704)]

## 🧑‍💻 F. Developer Support Behaviour

### Q28. Does Google Pay reply to most users or only some?

In [39]:
gpay['reply'].notna().mean() * 100

np.float64(17.85672548790464)

### Q29. Are complaints prioritised over compliments?

In [40]:
pd.crosstab(gpay['score'], gpay['reply'].notna(), normalize=True) * 100

reply      False      True
score
1      12.410892  12.767325
2       2.302209   2.351876
3       3.736707   1.896108
4       8.595302   0.295080
5      55.098165   0.546336

### Q30. Are 1★ reviews almost always replied?

In [41]:
gpay[gpay['score']==1]['reply'].notna().mean() * 100

np.float64(50.707820840102116)

### Q31. Does the company ignore positive feedback?

In [42]:
gpay[gpay['score']>=4]['reply'].notna().mean() * 100

np.float64(1.3038163791932635)

### Q32. Is support reactive (only after outrage) or consistent?

In [43]:
gpay.groupby('score')['reply'].apply(lambda x:x.notna().mean())

score
1    0.507078
2    0.505336
3    0.336618
4    0.033191
5    0.009818
Name: reply, dtype: float64

## ⏱️ G. Support Efficiency

### Q33. How fast does Google Pay respond on average?

In [44]:
review_time = pd.to_datetime(gpay[['year','month','day','hour']])
reply_time = pd.to_datetime(gpay[['reply_yr','reply_month','reply_day','reply_hour']].rename(
    columns={'reply_yr': 'year', 'reply_month': 'month', 'reply_day': 'day', 'reply_hour': 'hour'}
))
gpay['resp_hour'] = (reply_time - review_time).dt.total_seconds()/3600
gpay['resp_hour'].mean()

np.float64(-509.52715968586386)

### Q34. Are critical issues handled faster?

In [45]:
gpay.groupby('score')['resp_hour'].mean()

score
1    -159.771167
2    -186.335404
3    -259.804314
4   -5760.227723
5   -8104.994652
Name: resp_hour, dtype: float64

### Q35. Are weekend complaints delayed?

In [47]:
gpay.groupby('week')['resp_hour'].mean()

week
Weekday   -532.889443
Weekend   -448.796231
Name: resp_hour, dtype: float64

### Q36. Does response time vary by day?

In [48]:
gpay.groupby('day_name')['resp_hour'].mean()

day_name
Friday      -459.053911
Monday      -590.932349
Saturday    -494.806452
Sunday      -397.027534
Thursday    -242.442604
Tuesday     -725.056920
Wednesday   -637.818381
Name: resp_hour, dtype: float64

### Q37. Does response timing align with complaint timing?

In [49]:
gpay.groupby('hour')['resp_hour'].mean()

hour
0     -163.424749
1     -534.249201
2     -535.748148
3     -828.925795
4     -240.493151
5     -509.486590
6     -313.990566
7    -1139.856436
8     -258.911765
9     -210.573099
10    -504.066265
11    -889.857143
12    -352.702929
13    -702.492386
14    -464.351695
15    -206.440329
16    -516.154472
17    -720.427481
18    -474.248322
19    -116.322464
20    -791.528481
21    -556.366102
22    -452.816199
23    -769.489097
Name: resp_hour, dtype: float64

## 🔗 H. Impact of Reply

### Q38. Do replied complaints get more agreement (thumbsups)?

In [50]:
gpay.groupby(gpay['reply'].notna())['thumbsups'].mean()

reply
False    2.664462
True     7.554810
Name: thumbsups, dtype: float64

### Q39. Does replying calm the community?

In [51]:
gpay[gpay['reply'].notna()].groupby('score')['thumbsups'].mean()

score
1     6.643249
2    10.513043
3     7.828968
4     7.891089
5    14.989305
Name: thumbsups, dtype: float64

### Q40. Are unanswered complaints more viral?

In [52]:
gpay[gpay['reply'].isna()].sort_values('thumbsups', ascending=False).head(10)

,id,username,content,score,thumbsups,reviewCreatedVersion,time,reply,repliedAt,year,...,reply_month,reply_month_name,reply_day,reply_day_name,reply_hour,sentiment,late_night,week,length,resp_hour
15523,15523,Angela McConaughy,This app will not open as of 06/14/2020. Out o...,2,1921,2.111.306893647,2020-06-17 22:58:56,NaN,NaT,2020,...,NaN,NaN,NaN,NaN,NaN,Negative,Day,Weekday,488,NaN
1784,1784,Sean Buckels,Remember when this app use to allow you to use...,1,1733,2.134.392709498,2021-09-09 21:03:07,NaN,NaT,2021,...,NaN,NaN,NaN,NaN,NaN,Negative,Day,Weekday,722,NaN
16863,16863,Brian Farenell,"Functions quite poorly. With Samsung Pay, the ...",2,1491,2.111.306893647,2020-05-28 20:27:56,NaN,NaT,2020,...,NaN,NaN,NaN,NaN,NaN,Negative,Day,Weekday,467,NaN
32734,32734,Ashley Wasylk,I am very disappointed with Google Pay. Recent...,1,973,2.99.274616458,2019-10-19 03:20:44,NaN,NaT,2019,...,NaN,NaN,NaN,NaN,NaN,Negative,Late-Night,Weekend,1836,NaN
30715,30715,alexander kolnogorov,Everything works fine now! But it LACKS Dark M...,5,840,2.100.275591585,2019-11-12 21:32:27,NaN,NaT,2019,...,NaN,NaN,NaN,NaN,NaN,Positive,Day,Weekday,88,NaN
33782,33782,Eric LaSarge,I like that google services are all connected....,4,775,2.98.272088169,2019-10-05 23:28:38,NaN,NaT,2019,...,NaN,NaN,NaN,NaN,NaN,Positive,Late-Night,Weekend,487,NaN
28779,28779,Suzanna Armstrong,I love this app. It makes it super convenient ...,5,672,2.103.282408549,2019-12-08 04:37:24,NaN,NaT,2019,...,NaN,NaN,NaN,NaN,NaN,Positive,Late-Night,Weekend,391,NaN
16796,16796,Neil Griffiths,Fine as long as it keeps working. Did 3 contac...,1,591,2.111.306893647,2020-05-29 16:47:42,NaN,NaT,2020,...,NaN,NaN,NaN,NaN,NaN,Negative,Day,Weekday,585,NaN
14155,14155,L A,There's a bit of lag when swiping through the ...,4,543,2.111.306893647,2020-07-09 13:47:52,NaN,NaT,2020,...,NaN,NaN,NaN,NaN,NaN,Positive,Day,Weekday,472,NaN
30807,30807,Adam Kelley,Not much to say in terms of use and functional...,5,510,2.101.277730300,2019-11-12 01:19:06,NaN,NaT,2019,...,NaN,NaN,NaN,NaN,NaN,Positive,Late-Night,Weekday,274,NaN

### Q41. Do fast replies reduce negativity?

In [53]:
gpay[['resp_hour','score']].corr()

           resp_hour     score
resp_hour   1.000000 -0.308853
score      -0.308853  1.000000

## 👥 I. User Behaviour

### Q42. Are repeat reviewers mostly complainers?

In [54]:
gpay['username'].value_counts().head(10)

username
A Google user    224
David              9
Daniel             9
John Smith         7
Michael            7
John McNeil        6
Chris              6
Mark               6
James              6
J B                6
Name: count, dtype: int64

### Q43. Do some users only leave negative reviews?

In [55]:
gpay.groupby('username')['score'].mean().sort_values().head(10)

username
المحترم يحترم           1.0
Jackie Hendrik kleen    1.0
Jack Humphreys          1.0
Jack Keane              1.0
Jack Kernel             1.0
Jack Rabbit             1.0
ايرسن سوفت              1.0
شانِ ربّی               1.0
محمد قیصرالحسینی        1.0
Сергей Полежаев         1.0
Name: score, dtype: float64

### Q44. Are loyal users defending the app?

In [56]:
gpay.groupby('username')['score'].mean().sort_values().tail(10)

username
Jack Swanger                                 5.0
戸上大輔                                         5.0
#HARUN #H #X #XO #WI #HARUNRUNE #EC1V #H1    5.0
陳佑易                                          5.0
#Gamers World.###                            5.0
#E2pNetwork Channel                          5.0
木村デリーサ                                       5.0
#Angel Heaven & Darkness                     5.0
桂瑋仁                                          5.0
沈黙の中で死ぬ                                      5.0
Name: score, dtype: float64

### Q45. Is feedback coming from many users or few loud users?

In [57]:
gpay['username'].value_counts().describe()

count    33182.000000
mean         1.031493
std          1.242003
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        224.000000
Name: count, dtype: float64

## 🧩 J. Combined Business Insights (Portfolio Gold Section)

### Q46. Exact period when the app is most unreliable

In [58]:
gpay.groupby(['day_name','hour'])['score'].mean().sort_values().head(10)

day_name   hour
Monday     12      3.240876
Tuesday    14      3.335484
Wednesday  20      3.359184
Sunday     13      3.387387
Tuesday    3       3.391129
Monday     8       3.409639
Tuesday    12      3.411765
Wednesday  0       3.413793
Saturday   12      3.433333
Tuesday    10      3.445087
Name: score, dtype: float64

### Q47. Exact period when the app performs best

In [59]:
gpay.groupby(['day_name','hour'])['score'].mean().sort_values().tail(10)

day_name   hour
Tuesday    6       3.834906
Wednesday  23      3.841912
Thursday   21      3.843621
Sunday     9       3.847826
Monday     1       3.858871
Sunday     10      3.868217
Tuesday    17      3.901478
Monday     10      3.905109
Wednesday  15      3.907514
Sunday     7       4.021978
Name: score, dtype: float64

### Q48. Whether support timing matches user frustration timing

In [60]:
complaint = gpay[gpay['score']==1]['hour'].value_counts()

In [61]:
support = gpay[gpay['reply'].notna()]['reply_hour'].value_counts()

In [62]:
pd.concat([complaint, support], axis=1)

      count  count
0.0     477    291
3.0     467    243
1.0     454    257
2.0     440    315
23.0    431    390
22.0    425    389
20.0    424    372
4.0     423    303
21.0    409    427
19.0    383    419
5.0     371    277
18.0    369    362
8.0     343     16
6.0     327     92
17.0    323    397
16.0    304    424
15.0    296    381
12.0    293     24
7.0     291    105
9.0     286     18
14.0    284    446
11.0    275     23
13.0    263    128
10.0    260     13

### Q49. Whether Google Pay prevents or reacts to crises

In [63]:
gpay[gpay['score']<=2]['resp_hour'].mean()

np.float64(-163.90338164251207)

In [64]:
gpay.groupby('score')['resp_hour'].mean()

score
1    -159.771167
2    -186.335404
3    -259.804314
4   -5760.227723
5   -8104.994652
Name: resp_hour, dtype: float64

### Q50. Overall trust level of the platform

In [65]:
(gpay['score'].mean(), gpay['thumbsups'].mean(), gpay['reply'].notna().mean())

(np.float64(3.651688675937829),
 np.float64(3.5377176580577303),
 np.float64(0.1785672548790464))